### PR TITLE
Fixes #2709: reword status to say "directory"

### LINKED ISSUE #2709: Remaining instance of "directory server"
In the translations, I've spotted the following:
```
        <location filename="../serverdlg.cpp" line="737"/>
        <source>Now a directory server</source>
```
The "Now a directory server" may be the last remaining instance of "directory server" usage - there should be none left.

**To Reproduce**

Look at `serverdlg.cpp` line 737.

**Expected behavior**

Should say `Now a directory`.

**Version of Jamulus**

master HEAD

**Additional context**

I'll try to fix this now...

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

Fixes three of the remaining references to "directory server" rather than "directory" in the code -- these are in messages, two of them requiring translation.

There is one I didn't change: `--directoryserver`.  I could change that, too.

There's a whole load of others in the code that don't get seen - those need changing, too, really, but not as part of this fix.

CHANGELOG: Fix (hopefully) all remaining references to "directory server" in displayed messages to say "directory"

**Context: Fixes an issue?**

Fixes: #2709 

**Does this change need documentation?**

Hopefully all documentation already refers to "directory" correctly.

**Status of this Pull Request**

Need to confirm scope.

**What is missing until this pull request can be merged?**

Decide when to merge it.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

File: src/util.h [hunk 1]
```diff
@@ -645,7 +645,7 @@ inline QString svrRegStatusToString ( ESvrRegStatus eSvrRegStatus )
         return QCoreApplication::translate ( "CServerDlg", "Registered" );
 
     case SRS_SERVER_LIST_FULL:
-        return QCoreApplication::translate ( "CServerDlg", "Directory Server full" );
+        return QCoreApplication::translate ( "CServerDlg", "Directory server list full" );
```
Comment (jujudusud) [inline src/util.h:648]: I'm not an english expert, but, isn't it `Server's list directory full` instead?

**Review by ann0see — COMMENTED** [review]
As it requires translation we need to tell the translators...

**Comment by pljones** [comment]
That's what triggered this -- seeing it in translation strings.

File: src/util.h (hunk 1 above)
Comment (pljones) [reply src/util.h:648]: No, that's wrong.  It's the Directory that holds a server list.  That's the point of a Directory.

**Review by ann0see — APPROVED** [review]

**Review by jujudusud — APPROVED** [review]

**Review by jujudusud — APPROVED** [review]

**Review by hoffie — APPROVED** [review]
- Should this PR also include updated files as produced by `lupdate`? Or did you avoid adding them intentionally?
- Merging this PR now will add additional work:
  - PRs where the translation was already updated despite the source string only changing here will likely show up for translation again.
  - PRs which are based on a commit which did not have this change are likely to have a conflict. The conflict can only be solved by the translator and not by maintainers.

I already saw that you (@pljones) have been mentoring some (all?) already submitted translation PRs, so I guess it'll be taken care of. Therefore, approving.

**Comment by pljones** [comment]
I left out the lrelease stuff to do separately with a new push to the translators.  Once I've done that to master, I'll update all the translator issues, re-opening where necessary.
