### PR TITLE
Typofixes

### LINKED ISSUE #1069: Translation typos
**Describe the bug**
The Dutch translation of Jamulus has some typos.

**To Reproduce**
- `Welkomsbericht` in 2 places must be `Welkomstbericht`
- `Vaardigheidssniveau` must be `Vaardigheidsniveau`

**Operating system**
all

**Version of Jamulus**
Jamulus, Version 3.6.2dev-373e1f48

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kwetal**
Fixes #1069.

### CODE REVIEW

**Review by jerogee — APPROVED** [review]

**Review by jerogee — APPROVED** [review]

File: src/res/translation/translation_nl_NL.ts [hunk 1]
```diff
@@ -276,7 +276,7 @@
     </message>
     <message>
         <source>Displays the pre-fader audio level of this channel.  All connected clients at the server will be assigned an audio level, the same value for each client.</source>
-        <translation type="vanished">Geeft het pre-fader-audioniveau van dit kanaal weer.  Alle verbonden clients op de server krijgen een audioniveau toegewezen, dezelfde waarde voor elke client.</translation>
+        <translation type="vanished">Geeft het pre-fader-audioniveau van dit kanaal weer. Alle verbonden clients op de server krijgen een audioniveau toegewezen, dezelfde waarde voor elke client.</translation>
```
Comment (pljones) [inline src/res/translation/translation_nl_NL.ts:279]: The English has two spaces for a new sentence here (which is fairly normal).  Does the Dutch _consistently_ only have one?  If not, I'd rather things were left alone until a decision is taken on which form to follow.

Comment (jerogee) [reply src/res/translation/translation_nl_NL.ts:279]: In Dutch, full stops are consistently followed by a single space. Using double spaces would look weird. There was a time (the age of typewriters), that double spaces after full stops were common in Dutch typewriting (like for English and other languages at the time) because a single monospaced typewriter space was not sufficient to show the larger inter-sentence space (the em-quad) that was commonly used in traditional typesetting of books. However, especially in Dutch it mostly disappeared after the dawn of computers. 

Interestingly, in French it is common to have spaces _precede_ exclamation points, question marks, colons, and semi-colons. For instance:

```xml
 187         <source>Personal Mix at: </source>¶
 188         <translation>Mixage personnel à : </translation>¶

2859         <source>Do you want to open the ASIO driver setups?</source>¶
2860         <translation>Voulez-vous ouvrir les configurations des pilotes ASIO ?</translation>¶
```

**Review by ann0see — APPROVED** [review]

File: src/res/translation/translation_nl_NL.ts (hunk 1 above)
Comment (gilgongo) [reply src/res/translation/translation_nl_NL.ts:279]: >  English has two spaces for a new sentence here (which is fairly normal)

That never occurred to me! :-) I'd [assumed](https://www.writing-skills.com/one-space-two-full-stop) we were using singles on Jamulus... I'm pretty sure we are?

Comment (trebmuh) [reply src/res/translation/translation_nl_NL.ts:279]: > Interestingly, in French it is common to have spaces precede exclamation points, question marks, colons, and semi-colons. 

Not only "common" but "obligatory" (since given by the French writing rules).

Comment (pljones) [reply src/res/translation/translation_nl_NL.ts:279]: > Not only "common" but "obligatory" 

And, being French, the punishments are probably quite severe ;)...

**Comment by ann0see** [comment]
@jamulussoftware/maindevelopers can anyone approve and merge this?

**Comment by gilgongo** [comment]
I'm going to come out and say that double spaces after full stops in English are not right. But I'll approve this PR :-)

**Review by gilgongo — APPROVED** [review]

**Comment by pljones** [comment]
> I'm going to come out and say that double spaces after full stops in English are not right. But I'll approve this PR :-)

I guess I was taught to type by people who learnt in the early-1950s -- probably from someone who was an adamant double-spacer herself (secretaries in those days - wartime - were generally female).  So it's just inherited style.

Anyway - in HTML, the double space gets eaten by the browser when painting.  I'm not going to be asking for `&emsp;`...

File: src/res/translation/translation_nl_NL.ts (hunk 1 above)
Comment (trebmuh) [reply src/res/translation/translation_nl_NL.ts:279]: Probably something very hard like... an English typographic writing lesson ;)
