### PR TITLE
Mute icon: Fix alignment by not hardcoding font height

### LINKED ISSUE #1312: Icon pushes the PAN control down
**Describe the bug**
Please see the third PAN control in the screenshot:
image

This isn't a big deal, just a small visual defect.

### PR DESCRIPTION
**Pull request by vimpostor**
Fixes #1312

**Before**: On the Left - Volume Sliders have mismatched height, Mute icon is slightly misaligned
**After**: On the Right - Volume Sliders and Mute icon are placed without weird misalignment
Screenshot_20210506_003727

Note that I tried some cleaner ways of fixing this misalignement - that is I tried not setting minimum height at all and using a more clever alignment. None of that worked though and I actually think there is a Qt bug when rendering Unicode symbols regarding the height of layouts.

Anyways, in the end I think this is the best method of solving the problem now.

### CODE REVIEW

**Comment by gilgongo** [comment]
Thanks for this! 

As a side issue, I've often wondered whether we could use an image and not a unicode character for the icon, since I would expect Qt to handle fonts with some kind of proportional leading (and they look different on different operating systems).

File: src/audiomixerboard.cpp [hunk 1]
```diff
@@ -86,9 +86,10 @@ CChannelFader::CChannelFader ( QWidget* pNW ) :
     pPan->setRange               ( 0, AUD_MIX_PAN_MAX );
     pPan->setValue               ( AUD_MIX_PAN_MAX / 2 );
     pPan->setNotchesVisible      ( true );
-    pInfoLabel->setMinimumHeight ( 15 ); // prevents jitter when muting/unmuting (#811)
-    pPanInfoGrid->addWidget      ( pPanLabel, 0, Qt::AlignLeft );
-    pPanInfoGrid->addWidget      ( pInfoLabel );
+    pInfoLabel->setMinimumHeight ( pPanLabel->height() ); // prevents jitter when muting/unmuting (#811)
+    pInfoLabel->setAlignment( Qt::AlignTop );
```
Comment (hoffie) [inline src/audiomixerboard.cpp:90]: Can you also align this similar to the other calls?

**Review by hoffie — COMMENTED** [review]
Thanks for this PR! :)
Can you confirm (maybe with a screenshot) that this also works properly for Mono setups without Pan widgets?

**Comment by vimpostor** [comment]
Screenshot of working mono setup as requested:
Screenshot_20210506_233339

I have also manually tested it to be working with all combinations of {mono,stereo} x {compact, modern, standard theme}

**Review by hoffie — APPROVED** [review]
Thanks! Looks good to me.

Do you want to list yourself in the [contributors list](https://github.com/jamulussoftware/jamulus/blob/master/src/util.cpp#L493)?
You can do this as part of this PR.

**Comment by vimpostor** [comment]
I am not sure, if such a small change warrants me being part of the contributors list, but I intend to submit more PRs to this project, so I might as well add myself now.
Done now in a separate commit. ;)

**Review by softins — APPROVED** [review]
Looks good, and I have tested on Linux.

**Comment by vimpostor** [comment]
I agree that the general UI of this could be improved on. Perhaps a mouseover hover text that explains what the icon means, would already be better.

**Comment by hoffie** [comment]
Maybe the [**previous discussion in #1251**](https://github.com/jamulussoftware/jamulus/discussions/1251) (generated from #933) should be revived so that a new PR can be created when there is consensus if and how to do this?

I suggest continuing thereas this is more likely to get some visibility than this closed PR :)
