### PR TITLE
Fix memory leaks in Jam Recorder

### LINKED ISSUE #1019: Recorder Memory leak: Investigate valgrind output
**Describe the bug**

`valgrind` shows that memory is leaked. It might be related to the jam recorder.
This is an attempt to reproduce the real-world memleaks as observed by @genesisproject2020 (~1GB RAM within ~25 hours) in https://github.com/jamulussoftware/jamulus/issues/923#issuecomment-780866034
valgrind ran ~10 minutes and the server had 7 clients connected (all sending silence).

**To Reproduce**
```
$ valgrind --leak-check=full ./Jamulus -s -n -p 10001 -e localhost:10000 -l /tmp/log -R /tmp/recordings -o 'Private Server;Stockholm;205' -m /tmp/jam.dat -u 40 -T -w 'Welcome!'
==129778== Memcheck, a memory error detector
==129778== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==129778== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==129778== Command: ./Jamulus -s -n -p 10001 -e localhost:10000 -l /tmp/log -R /tmp/recordings -o Private\ Server;Stockholm;205 -m /tmp/jam.dat -u 40 -T -w Welcome!
==129778== 
- server mode chosen
- no GUI mode chosen
- selected port number: 10001
- central server: localhost:10000
- logging file name: /tmp/log
- recording directory name: /tmp/recordings
- server info: Private Server;Stockholm;205
- HTML status file name: /tmp/jam.dat
- maximum number of channels: 40
- using multithreading
- welcome message: Welcome!
Recording state: enabled
 *** Jamulus, Version 3.6.2dev-83d5f0cf
 *** Internet Jam Session Software
 *** Released under the GNU General Public License (GPL)
Server Registration Status update: Registration requested
Server Registration Status update: Registered
2021-02-18 23:36:37, 127.0.0.1, connected (1)
2021-02-18 23:36:38, 127.0.0.1, connected (2)
2021-02-18 23:36:47, 127.0.0.1, connected (3)
2021-02-18 23:36:50, 127.0.0.1, connected (5)
2021-02-18 23:36:54, 127.0.0.1, connected (7)
2021-02-18 23:36:59, 127.0.0.1, connected (7)
2021-02-18 23:37:09, 127.0.0.1, connected (7)
^C2021-02-18 23:47:50,, server idling -------------------------------------
Session RPP: "/tmp/recordings/Jam-20210218-223637790/Jam-20210218-223637790.rpp"
Session LOF: "/tmp/recordings/Jam-20210218-223637790/Jam-20210218-223637790.lof"
Server Registration Status update: Registration requested
OnHandledSignal: 2
Server Registration Status update: Unregistered
==129778== 
==129778== HEAP SUMMARY:
==129778==     in use at exit: 8,563,566 bytes in 1,266 blocks
==129778==   total heap usage: 12,369,339 allocs, 12,368,073 frees, 3,617,858,812 bytes allocated
==129778== 
==129778== 352 bytes in 1 blocks are possibly lost in loss record 115 of 165
==129778==    at 0x483CB65: calloc (vg_replace_malloc.c:760)
==129778==    by 0x40142EB: _dl_allocate_tls (in /usr/lib/ld-2.32.so)
==129778==    by 0x48C913C: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.32.so)
==129778==    by 0x58D79A2: QThread::start(QThread::Priority) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x15B782: CServer::CServer(int, QString const&, unsigned short, QString const&, QString const&, QString const&, QString const&, QString const&, QString const&, QString const&, bool, bool, bool, bool, ELicenceType) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x13BD6F: main (in /home/christian/Projects/jamulus/Jamulus)
==129778== 
==129778== 352 bytes in 1 blocks are possibly lost in loss record 116 of 165
==129778==    at 0x483CB65: calloc (vg_replace_malloc.c:760)
==129778==    by 0x40142EB: _dl_allocate_tls (in /usr/lib/ld-2.32.so)
==129778==    by 0x48C913C: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.32.so)
==129778==    by 0x58D79A2: QThread::start(QThread::Priority) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x155EFF: CServer::Start() (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC4BE: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5B190A3: ??? (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x7147A83: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x719B9B0: ??? (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x71462B0: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778== 
==129778== 392 bytes in 7 blocks are definitely lost in loss record 118 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x1AD536: recorder::CJamClient::CJamClient(long long, int, QString, CHostAddress, QDir) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AEAB7: recorder::CJamSession::Frame(int, QString, CHostAddress, int, CVector<short>, int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1B18C6: recorder::CJamRecorder::OnFrame(int, QString, CHostAddress, int, CVector<short>) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x155B5A: QtPrivate::QSlotObject<void (recorder::CJamRecorder::*)(int, QString, CHostAddress, int, CVector<short>), QtPrivate::List<int, QString, CHostAddress, int, CVector<short> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5B190A3: ??? (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x7147A83: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x719B9B0: ??? (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x71462B0: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778== 
==129778== 438 (88 direct, 350 indirect) bytes in 1 blocks are definitely lost in loss record 120 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x5AF54E5: QObject::QObject(QObject*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x1ADF21: recorder::CJamSession::DisconnectClient(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AE1A8: recorder::CJamRecorder::OnDisconnected(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5B190A3: ??? (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x7147A83: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x719B9B0: ??? (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x71462B0: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x5B186FB: QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (in /usr/lib/libQt5Core.so.5.15.2)
==129778== 
==129778== 876 (112 direct, 764 indirect) bytes in 2 blocks are definitely lost in loss record 129 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x1ADF14: recorder::CJamSession::DisconnectClient(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AE1A8: recorder::CJamRecorder::OnDisconnected(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5B190A3: ??? (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x7147A83: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x719B9B0: ??? (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x71462B0: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x5B186E0: QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABE3FB: QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (in /usr/lib/libQt5Core.so.5.15.2)
==129778== 
==129778== 1,056 bytes in 3 blocks are possibly lost in loss record 136 of 165
==129778==    at 0x483CB65: calloc (vg_replace_malloc.c:760)
==129778==    by 0x40142EB: _dl_allocate_tls (in /usr/lib/ld-2.32.so)
==129778==    by 0x48C913C: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.32.so)
==129778==    by 0x58D79A2: QThread::start(QThread::Priority) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x58DA754: QThreadPoolPrivate::startThread(QRunnable*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x58DBB13: QThreadPoolPrivate::tryStart(QRunnable*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x58DC327: QThreadPool::start(QRunnable*, int) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x19171F: QFuture<void> QtConcurrent::run<void, CServer, int, int, int, int, int, int>(CServer*, void (CServer::*)(int, int, int), int const&, int const&, int const&) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x159343: CServer::OnTimer() (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778== 
==129778== 1,744 (352 direct, 1,392 indirect) bytes in 4 blocks are definitely lost in loss record 146 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x5AF54E5: QObject::QObject(QObject*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x1ADF21: recorder::CJamSession::DisconnectClient(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AE1A8: recorder::CJamRecorder::OnDisconnected(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5B190A3: ??? (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x7147A83: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x719B9B0: ??? (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x71462B0: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6600.4)
==129778==    by 0x5B186E0: QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (in /usr/lib/libQt5Core.so.5.15.2)
==129778== 
==129778== 1,824 (16 direct, 1,808 indirect) bytes in 1 blocks are definitely lost in loss record 147 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x154EE1: recorder::CJamController::SetRecordingDir(QString, int, bool) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x15A749: CServer::CServer(int, QString const&, unsigned short, QString const&, QString const&, QString const&, QString const&, QString const&, QString const&, QString const&, bool, bool, bool, bool, ELicenceType) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x13BD6F: main (in /home/christian/Projects/jamulus/Jamulus)
==129778== 
==129778== 9,856 bytes in 28 blocks are possibly lost in loss record 162 of 165
==129778==    at 0x483CB65: calloc (vg_replace_malloc.c:760)
==129778==    by 0x40142EB: _dl_allocate_tls (in /usr/lib/ld-2.32.so)
==129778==    by 0x48C913C: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.32.so)
==129778==    by 0x58D79A2: QThread::start(QThread::Priority) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x58DA754: QThreadPoolPrivate::startThread(QRunnable*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x58DBB13: QThreadPoolPrivate::tryStart(QRunnable*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x58DC327: QThreadPool::start(QRunnable*, int) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x19171F: QFuture<void> QtConcurrent::run<void, CServer, int, int, int, int, int, int>(CServer*, void (CServer::*)(int, int, int), int const&, int const&, int const&) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x158FC5: CServer::OnTimer() (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5ABFA4F: QCoreApplication::notifyInternal2(QObject*, QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x5AC2572: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778== 
==129778== LEAK SUMMARY:
==129778==    definitely lost: 960 bytes in 15 blocks
==129778==    indirectly lost: 4,314 bytes in 31 blocks
==129778==      possibly lost: 11,616 bytes in 33 blocks
==129778==    still reachable: 8,546,676 bytes in 1,187 blocks
==129778==         suppressed: 0 bytes in 0 blocks
==129778== Reachable blocks (those to which a pointer was found) are not shown.
==129778== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==129778== 
==129778== For lists of detected and suppressed errors, rerun with: -s
==129778== ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 0 from 0)
```

**Expected behavior**
No leak.

**Operating system**

Arch Linux, Linux wuechoo 5.10.9-arch1-1 #1 SMP PREEMPT Tue, 19 Jan 2021 22:06:06 +0000 x86_64 GNU/Linux

**Version of Jamulus**
3.6.2dev-83d5f0cf

### PR DESCRIPTION
**Pull request by softins**
Fixes #1019 

EDIT: fixes leaks in the recorder, but there appear still to be others.

### CODE REVIEW

**Comment by genesisproject2020** [comment]
I've compiled the updated code and put it live on Swedish Open Jam 1 and 2. Now just waiting to see what's happens.

File: src/recorder/jamcontroller.cpp [hunk 1]
```diff
@@ -77,15 +78,25 @@ void CJamController::SetRecordingDir ( QString newRecordingDir,
...
+            // We have a thread and we want to start a new one.
+            // We only want one running.
+            // This could take time, unfortunately.
+            // Hopefully changing recording directory will NOT happen during a long jam...
+            emit EndRecorderThread();
+            pthJamRecorder->wait();
+            delete pthJamRecorder;
+            pthJamRecorder = nullptr;
+        }
+        if ( pJamRecorder != nullptr )
```
Comment (pljones) [inline src/recorder/jamcontroller.cpp:94]: Not sure about this new bit.  Can you explain why you lose the JamRecorder main thread reference?

File: src/recorder/jamrecorder.cpp [hunk 2]
```diff
@@ -77,7 +78,7 @@ void CJamClient::Frame(const QString _name, const CVector<int16_t>& pcm, int iSe
 
     for(int i = 0; i < numChannels * iServerFrameSizeSamples; i++)
     {
-        *out << pcm[i];
+        if (out) *out << pcm[i];
```
Comment (pljones) [inline src/recorder/jamrecorder.cpp:81]: This shouldn't be necessary - it looks like it's losing data.  That mustn't happen.

File: src/recorder/jamrecorder.cpp [hunk 3]
```diff
@@ -88,8 +89,12 @@ void CJamClient::Frame(const QString _name, const CVector<int16_t>& pcm, int iSe
  */
 void CJamClient::Disconnect()
 {
-    static_cast<CWaveStream*>(out)->finalise();
-    out = nullptr;
+    if (out)
+    {
+        static_cast<CWaveStream*>(out)->finalise();
```
Comment (pljones) [inline src/recorder/jamrecorder.cpp:94]: This waits, right?  So long as that's true, we're okay...

File: src/recorder/jamrecorder.cpp [hunk 4]
```diff
@@ -134,6 +139,21 @@ CJamSession::CJamSession(QDir recordBaseDir) :
...
+/**
+ * @brief CJamSession::~CJamSession
+ */
+CJamSession::~CJamSession()
+{
+    for (int i = 0; i < jamClientConnections.count(); i++ )
+    {
+        if ( jamClientConnections[i] )
+        {
+            delete jamClientConnections[i];
```
Comment (pljones) [inline src/recorder/jamrecorder.cpp:151]: This feels risky - do we know the connections have completed writing?  Will this wait for them to do so?

File: src/recorder/jamrecorder.cpp (hunk 2 above)
Comment (softins) [reply src/recorder/jamrecorder.cpp:81]: I just don't like to follow a pointer unless I am certain it is non-null. If the constructor throws an exception, `out` might not be set. Just belt and braces really - defensive programming.

File: src/recorder/jamcontroller.cpp (hunk 1 above)
Comment (softins) [reply src/recorder/jamcontroller.cpp:94]: The old code discarded the value of `pthJamRecorder` without freeing what it was pointing to. That was one of the leaks. Nowhere else was pointing to it, as far as I could tell.

File: src/recorder/jamrecorder.cpp (hunk 3 above)
Comment (softins) [reply src/recorder/jamrecorder.cpp:94]: Again, it's the same as the old code, except that:
1. It checks `out` before using it, and
2. It frees what `out` was pointing to before discarding the value of `out`. That was the other main leak.

File: src/recorder/jamrecorder.cpp (hunk 4 above)
Comment (softins) [reply src/recorder/jamrecorder.cpp:151]: Maybe there is another check to be made? But certainly we don't want to destroy the `CJamSession` instance without freeing the client connections it is pointing to.

File: src/recorder/jamcontroller.cpp (hunk 1 above)
Comment (pljones) [reply src/recorder/jamcontroller.cpp:94]: pthJamRecorder and pJamRecorder are different things.  You've added code for pJamRecorder.  That's what I'm questioning.  I understand the pthJamRecorder (thread-specific) code.

File: src/recorder/jamrecorder.cpp (hunk 2 above)
Comment (pljones) [reply src/recorder/jamrecorder.cpp:81]: That needs to be ensured elsewhere.  This mustn't be called without `*out` being valid - if it's been freed elsewhere, someone broke something.

File: src/recorder/jamrecorder.cpp (hunk 3 above)
Comment (pljones) [reply src/recorder/jamrecorder.cpp:94]: Ah sorry, yes.

File: src/recorder/jamrecorder.cpp (hunk 4 above)
Comment (pljones) [reply src/recorder/jamrecorder.cpp:151]: Actually, thinking now, this looks okay - it's only called when the CJamSession instance is being destroy _anyway_, so everything it owned should already have finished work - otherwise something already went badly wrong.

File: src/recorder/jamcontroller.cpp (hunk 1 above)
Comment (softins) [reply src/recorder/jamcontroller.cpp:94]: That's because a couple of lines further down there is:
```
pJamRecorder = new recorder::CJamRecorder ( newRecordingDir, iServerFrameSizeSamples );
```
which will leak whatever `pJamRecorder` was pointing to before. So my addition cleans it up before it gets overwritten.

File: src/recorder/jamrecorder.cpp (hunk 2 above)
Comment (softins) [reply src/recorder/jamrecorder.cpp:81]: It shouldn't be freed anywhere else except in `CJamClient::Disconnect()`. And maybe the check here isn't necessary if it would never be called unless `CJamClient::CJamClient()` succeeds without an exception. Happy to remove the test, as the code has been there a long time and there have been no reports of any crashes due to using a null `out` here. Perhaps if we do want to keep the test it should be in the three `operator <<` methods in `cwavestream.cpp`. But even that may be overkill, if none of these functions will ever be called unless `CJamClient()` succeeded.

File: src/recorder/jamcontroller.cpp (hunk 1 above)
Comment (pljones) [reply src/recorder/jamcontroller.cpp:94]: But that won't always happen - `if (!newRecordingDir.isEmpty())`.  Any management of `pJamRecorder` should be just before creating a new one.

File: src/recorder/jamcontroller.cpp [hunk 5]
```diff
@@ -77,15 +78,25 @@ void CJamController::SetRecordingDir ( QString newRecordingDir,
...
+        {
+            // We have a recorder running already. Terminate it.
+            delete pJamRecorder;
+            pJamRecorder = nullptr;
+        }
     }
 
     if ( !newRecordingDir.isEmpty() )
```
Comment (pljones) [inline src/recorder/jamcontroller.cpp:102]: So inside this block, on the next line, check `if (pJamRecorder != null) { delete pJamRecorder; pJamRecorder = nullptr; }`.

Comment (pljones) [reply src/recorder/jamcontroller.cpp:102]: (The CJamRecorder instance is long running: normally for the duration of the Jamulus main process.)

Comment (softins) [reply src/recorder/jamcontroller.cpp:102]: Ok, that's fine, I can move it to there. I'll check the detail tomorrow.

File: src/recorder/jamcontroller.cpp (hunk 1 above)
Comment (softins) [reply src/recorder/jamcontroller.cpp:94]: See comment below...

File: src/recorder/jamrecorder.cpp (hunk 2 above)
Comment (pljones) [reply src/recorder/jamrecorder.cpp:81]: Yup - it's my "It should just work, hasn't appeared broken, don't change it" approach :).

**Review by hoffie — APPROVED** [review]
Looks good to me! I can confirm that the following leaks no longer appear in valgrind after this PR. I therefore suggest merging this and continue leak hunting afterwards. :)

```==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x1AD536: recorder::CJamClient::CJamClient(long long, int, QString, CHostAddress, QDir) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AEAB7: recorder::CJamSession::Frame(int, QString, CHostAddress, int, CVector<short>, int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1B18C6: recorder::CJamRecorder::OnFrame(int, QString, CHostAddress, int, CVector<short>) (in /home/christian/Projects/jamulus/Jamulus)
```
```
==129778== 438 (88 direct, 350 indirect) bytes in 1 blocks are definitely lost in loss record 120 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x5AF54E5: QObject::QObject(QObject*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x1ADF21: recorder::CJamSession::DisconnectClient(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AE1A8: recorder::CJamRecorder::OnDisconnected(int) (in /home/christian/Projects/jamulus/Jamulus)
```

```
==129778== 876 (112 direct, 764 indirect) bytes in 2 blocks are definitely lost in loss record 129 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x1ADF14: recorder::CJamSession::DisconnectClient(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AE1A8: recorder::CJamRecorder::OnDisconnected(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x5AEC581: QObject::event(QEvent*) (in /usr/lib/libQt5Core.so.5.15.2)

```
==129778== 1,744 (352 direct, 1,392 indirect) bytes in 4 blocks are definitely lost in loss record 146 of 165
==129778==    at 0x483ADEF: operator new(unsigned long) (vg_replace_malloc.c:342)
==129778==    by 0x5AF54E5: QObject::QObject(QObject*) (in /usr/lib/libQt5Core.so.5.15.2)
==129778==    by 0x1ADF21: recorder::CJamSession::DisconnectClient(int) (in /home/christian/Projects/jamulus/Jamulus)
==129778==    by 0x1AE1A8: recorder::CJamRecorder::OnDisconnected(int) (in /home/christian/Projects/jamulus/Jamulus)
```

File: src/recorder/jamcontroller.cpp [hunk 6]
```diff
@@ -77,19 +78,29 @@ void CJamController::SetRecordingDir ( QString newRecordingDir,
...
+    if ( bRecorderInitialised )
     {
-        // We have a thread and we want to start a new one.
-        // We only want one running.
-        // This could take time, unfortunately.
-        // Hopefully changing recording directory will NOT happen during a long jam...
-        emit EndRecorderThread();
-        pthJamRecorder->wait();
-        pthJamRecorder = nullptr;
+        if ( pthJamRecorder != nullptr )
```
[the remark this answers is not in the document]
Comment (pljones) [reply src/recorder/jamcontroller.cpp:83]: Yes, then it's just the addition of the `delete` line, too.

File: src/recorder/jamcontroller.cpp [hunk 7]
```diff
@@ -77,19 +78,29 @@ void CJamController::SetRecordingDir ( QString newRecordingDir,
...
+            pthJamRecorder = nullptr;
+        }
     }
 
     if ( !newRecordingDir.isEmpty() )
     {
+        if ( pJamRecorder != nullptr )
+        {
+            // We have a recorder running already. Terminate it.
+            delete pJamRecorder;
```
Comment (pljones) [inline src/recorder/jamcontroller.cpp:101]: Does this cause `CJamRecorder::OnAboutToQuit()` to be called?

File: src/recorder/jamcontroller.cpp [hunk 8]
```diff
@@ -77,19 +78,29 @@ void CJamController::SetRecordingDir ( QString newRecordingDir,
...
+            delete pthJamRecorder;
+            pthJamRecorder = nullptr;
+        }
     }
 
     if ( !newRecordingDir.isEmpty() )
     {
+        if ( pJamRecorder != nullptr )
+        {
+            // We have a recorder running already. Terminate it.
```
Comment (pljones) [inline src/recorder/jamcontroller.cpp:100]: Just so I don't get so nervous reading this, can it be a clearer comment, please:
`// We have a reference to a CJamRecorder instance that should now have finished.  Clean up the instance.`
(`pJamRecorder->moveToThread ( pthJamRecorder );` puts `pJamRecorder` into the thread and the `pthJamRecorder ->wait()` above - if we had one - waited for it to finish.)

File: src/recorder/jamcontroller.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (softins) [reply src/recorder/jamcontroller.cpp:83]: Can do now. I split it when I wanted to test for both `pthJamRecorder` and `pJamRecorder`. Now the latter has been moved, we can go back to the original way.

**Review by pljones — APPROVED** [review]
