### PR TITLE
Client: Always update gain levels

### LINKED ISSUE #955: Restarting the server on the fly ignores set levels and mixes everybody at 100%
**Describe the bug**
Restarting the server sets levels to 100%

**To Reproduce**
restart a running server with clients on it and notice how it ignores the set gain levels and mixes everybody at 100%

**Expected behavior**
the server should mix everybody at the individually set levels

**Operating system**
linux, windows, macos

**Version of Jamulus**
3.6.2 and before

### PR DESCRIPTION
**Pull request by hoffie**
Previously, gain levels had only been updated when a channel's name changed. This lead to missing gain level updates when reconnecting to a restarted server. Therefore, always update gain levels when receiving a new channel list.

Fixes #955.

Note: This is an alternative approach to #1010. Both PRs are compatible and can be merged together.

### CODE REVIEW

File: src/audiomixerboard.cpp [hunk 1]
```diff
@@ -1174,30 +1174,27 @@ void CAudioMixerBoard::ApplyNewConClientList ( CVector<CChannelInfo>& vecChanInf
                         }
                     }
 
-                    // restore gain (if new name is different from the current one)
-                    if ( vecpChanFader[i]->GetReceivedName().compare ( vecChanInfo[j].strName ) )
```
Comment (hoffie) [inline src/audiomixerboard.cpp:1178]: The diff looks larger than it is. Essentially, this `if` is replaced by an `if ( true ) `. `git show -w bd081647b2152f9a430c4c59bb0b98a035d2cade` will be more readable than Github. :)

Comment (pljones) [reply src/audiomixerboard.cpp:1178]: Why doesn't Github have an "ignore whitespace".....?!

Comment (hoffie) [reply src/audiomixerboard.cpp:1178]: Just learned that Github actually supports this! :)

https://github.blog/2018-05-01-ignore-white-space-in-code-review/

https://github.com/jamulussoftware/jamulus/pull/1009/files?w=1

**Review by softins — APPROVED** [review]

**Review by pljones — APPROVED** [review]
