### PR TITLE
Bugfix: Ensure proper IPv6 obfuscation

### LINKED ISSUE #2342: Server-recorded project wav filenames show full IPv6 address
**Describe the bug**

I recorded a jam last night and after downloading the project to my local DAW, I discovered the wav file generated by my clients connection displayed the whole IPv6 address of the client, unlike the filename of the client using legacy IP address:

```
ardy@host:~(0)$ ll Jam-20220126-234046629/
total 122472
drwxr-xr-x 2 ardy ardy     4096 Jan 27 14:44 ./
drwxrwxr-x 3 ardy ardy     4096 Jan 27 13:38 ../
-rw-r--r-- 1 ardy ardy 62696492 Jan 27 13:38 Hey_Joe_-75_163_73_x_22175-1-2.wav
-rw-r--r-- 1 ardy ardy      158 Jan 27 13:38 Jam-20220126-234046629.lof
-rw-r--r-- 1 ardy ardy     5617 Jan 27 14:44 Jam-20220126-234046629.rpp
-rw-r--r-- 1 ardy ardy 62696492 Jan 27 13:38 RickD-2001_1055_8000_df70_1ad6_c7ff_fe01_a562_x_22217-0-2.wav
```
As shown above, the legacy IP has it's last octet masked but on the IPv6 address all 8 nybbles are shown and the _x_ is masking what?

**To Reproduce**

Enable recording and IPv6 on the server, connect IPv6 client, play.

**Expected behavior**

Filenames generated by recording from IPv6 clients to have last nybble obfuscated, just as last octet in legacy IP is obfuscated.

**Screenshots**

**Operating system**

Fedora Server 34. Jamulus 3.8.1 compiled from source.

**Version of Jamulus**

Jamulus 3.8.1 compiled from source using `qmake-qt5 "CONFIG+=noupcasename headless nosound" Jamulus.pro`.

**Additional context**

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

- util: Move CHostAddress implementation from .h to .cpp
- util: Fix IPv6 obfuscation in CHostAddress::toString

**Context: Fixes an issue?**

Fixes #2342

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready, but needs testing.

**What is missing until this pull request can be merged?**

- [x] Testing the logic (see below)
- [x] Testing IPv4 Recorder clients @rdica? :)
- [x] Testing IPv6 Recorder clients @rdica? :)
- [x] Decision if it should go into 3.8.2

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

---
I've tested the logic like that:

```diff
diff --git a/src/main.cpp b/src/main.cpp
index e63300c6..566099af 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -48,6 +48,24 @@ extern void qt_set_sequence_auto_mnemonic ( bool bEnable );
 int main ( int argc, char** argv )
 {
 
+    QList<QString> tests;
+    tests << QString ( "1.2.3.4" );
+    tests << QString ( "::1" );
+    tests << QString ( "::ffff:1.2.3.4" );
+    tests << QString ( "abcd::1234" );
+    tests << QString ( "1111:2222:3333:4444:5555:6666:7777:8888" );
+    foreach ( auto test, tests )
+    {
+        qInfo() << test << "->" << ( CHostAddress ( QHostAddress ( test ), 9999 ) ).toString ( CHostAddress::SM_IP_NO_LAST_BYTE );
+    }
+
+    foreach ( auto test, tests )
+    {
+        qInfo() << test << "(+port) ->" << ( CHostAddress ( QHostAddress ( test ), 9999 ) ).toString ( CHostAddress::SM_IP_NO_LAST_BYTE_PORT );
+    }
+
+    exit ( 0 );
+
 #if defined( Q_OS_MACX )
     // Mnemonic keys are default disabled in Qt for MacOS. The following function enables them.
     // Qt will not show these with underline characters in the GUI on MacOS.

```

Result:
```
"1.2.3.4" -> "1.2.3.x"
"::1" -> "::1"
"::ffff:1.2.3.4" -> "::ffff:1.2.3.x"
"abcd::1234" -> "abcd::x"
"1111:2222:3333:4444:5555:6666:7777:8888" -> "1111:2222:3333:4444:5555:6666:7777:x"
"1.2.3.4" (+port) -> "1.2.3.x:9999"
"::1" (+port) -> "[::1]:9999"
"::ffff:1.2.3.4" (+port) -> "::ffff:1.2.3.x:9999"
"abcd::1234" (+port) -> "[abcd::x]:9999"
"1111:2222:3333:4444:5555:6666:7777:8888" (+port) -> "[1111:2222:3333:4444:5555:6666:7777:x]:9999"
```

### CODE REVIEW

File: src/util.cpp [hunk 1]
```diff
@@ -942,6 +942,36 @@ int CHostAddress::Compare ( const CHostAddress& other ) const
...
+QString CHostAddress::toString ( const EStringMode eStringMode ) const
+{
+    QString strReturn = InetAddr.toString();
+
+    // special case: for local host address, we do not replace the last byte
+    if ( ( ( eStringMode == SM_IP_NO_LAST_BYTE ) || ( eStringMode == SM_IP_NO_LAST_BYTE_PORT ) ) &&
+         ( InetAddr != QHostAddress ( QHostAddress::LocalHost ) ) && ( InetAddr != QHostAddress ( QHostAddress::LocalHostIPv6 ) ) )
+    {
+        // replace last part by an "x"
+        if ( strReturn.contains ( "." ) )
```
Comment (hoffie) [inline src/util.cpp:954]: We could also check `InetAddr.protocol()`, but I think checking the `toString()` result for the actual characters which we need for properly working with this is better for the simple reason that we cannot fully reason about the exact output format of `InetAddr.toString()`.

File: src/util.cpp [hunk 2]
```diff
@@ -942,6 +942,36 @@ int CHostAddress::Compare ( const CHostAddress& other ) const
...
+        {
+            // IPv4 or IPv4-mapped:
+            strReturn = strReturn.section ( ".", 0, -2 ) + ".x";
+        }
+        else
+        {
+            // IPv6
+            strReturn = strReturn.section ( ":", 0, -2 ) + ":xxxx";
```
[the remark this answers is not in the document]
Comment (rdica) [reply src/util.cpp:962]: I thought about this when writing up the report. in IPv4 a host is assigned a single IP. Obfuscating on the last octet (/24) is more than sufficient for privacy.

In IPv6, the provider usually provisions at minimum a /64 per customer. The client's CPE will then autoconfigure hosts behind it with a unique IPv6 address out of the /64. I initially thought obfuscating from the fourth nybble (2001_db8_1234_5678_xxxx) might be the way to go, even if there are multiple clients connecting from same network. However, that /64 defines a single ISP customers network.
Not sure how you'll want to define privacy in that context.

**Comment by gilgongo** [comment]
Assuming this is ready for test in the next few days, it feels like we can get it into 3.8.2 as we still have 2 weeks.

File: src/util.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (hoffie) [reply src/util.cpp:962]: >  Not sure how you'll want to define privacy in that context.

Yep, that's a general question which is a bit easier to answer for IPv4 (*just drop 1/4 of the entropy*).
If the goal is being unable to have a working (pingable) IP address in the file names, this PR should be enough.
If the remaing parts of the IP address are expected to prevent people from associating this with another (known) full address of a person, this might not be sufficient for IPv6.

However, I feel that answering this question is hard, so my tendency would be to merge this PR as-is as it fixes a bug (wrong `_x`) and improves things (drops one nibble). If someone has a better idea on how to do the obfuscation, we could always implement that in a follow-up PR.

**Comment by pljones** [comment]
@softins Can you give this a review as you did a lot of the IPv6 stuff so far.

File: src/util.cpp [hunk 3]
```diff
@@ -942,6 +942,36 @@ int CHostAddress::Compare ( const CHostAddress& other ) const
...
+        }
+    }
+
+    if ( ( eStringMode == SM_IP_PORT ) || ( eStringMode == SM_IP_NO_LAST_BYTE_PORT ) )
+    {
+        // add port number after a semicolon
```
Comment (softins) [inline src/util.cpp:968]: Longstanding typo, but we might as well fix it: ":" is a colon, not a semicolon.

File: src/util.cpp [hunk 4]
```diff
@@ -942,6 +942,36 @@ int CHostAddress::Compare ( const CHostAddress& other ) const
...
+        strReturn += ":" + QString().setNum ( iPort );
```
Comment (softins) [inline src/util.cpp:969]: Although it probably doesn't matter for recording filenames (which convert most punctuation), if this is used anywhere else, we ought to make the output compatible with what can be given as input for IP:port. That means for IPv6, we need to enclose the address in `[ ]` before appending `:port`.
```suggestion
        if ( strReturn.contains ( "." ) )
        {
            strReturn += ":" + QString().setNum ( iPort );
        }
        else
        {
            // enclose pure IPv6 address in [ ] before adding port, to avoid ambiguity
            strReturn = "[" + strReturn + "]:" + QString().setNum ( iPort );
        }
```

**Review by softins — COMMENTED** [review]
Just a couple of comments. Otherwise looks good, and nice to get the function moved from `.h` to `.cpp`,

File: src/util.cpp (hunk 4 above)
Comment (hoffie) [reply src/util.cpp]: Thanks, committed! :)

File: src/util.cpp (hunk 3 above)
Comment (hoffie) [reply src/util.cpp]: Thanks, fixed.

File: src/util.cpp [hunk 5]
```diff
@@ -942,6 +942,44 @@ int CHostAddress::Compare ( const CHostAddress& other ) const
...
+    if ( ( ( eStringMode == SM_IP_NO_LAST_BYTE ) || ( eStringMode == SM_IP_NO_LAST_BYTE_PORT ) ) &&
+         ( InetAddr != QHostAddress ( QHostAddress::LocalHost ) ) && ( InetAddr != QHostAddress ( QHostAddress::LocalHostIPv6 ) ) )
+    {
+        // replace last part by an "x"
+        if ( strReturn.contains ( "." ) )
+        {
+            // IPv4 or IPv4-mapped:
+            strReturn = strReturn.section ( ".", 0, -2 ) + ".x";
+        }
+        else
```
Comment (pljones) [inline src/util.cpp:959]: What happens if `strReturn` has _neither` "." nor ":"?  This second block won't work...

Comment (softins) [reply src/util.cpp:959]: Is it even possible for `InetAddr.toString()` to return a string that contains neither `'.'` nor `':'`?

**Comment by softins** [comment]
Actually, one final thought. IPv6 addresses do not include leading zeros, just like IPv4 addresses don't. So an IPv6 address could be somethng like `2001:56:8::44:9`. By that token, I don't think we need `:xxxx`, and `:x` would be perfectly fine.

**Comment by hoffie** [comment]
> Actually, one final thought. IPv6 addresses do not include leading zeros, just like IPv4 addresses don't. So an IPv6 address could be somethng like `2001:56:8::44:9`. By that token, I don't think we need `:xxxx`, and `:x` would be perfectly fine.

Done, test output updated above.

**Review by pljones — APPROVED** [review]
